#ifndef CPLUSPLUS_BASE_LIBRARY_GLOBAL_HPP
#define CPLUSPLUS_BASE_LIBRARY_GLOBAL_HPP

#include <boost/config.hpp>

#if defined(CPLUSPLUS_BASE_LIBRARY_LIBRARY)
#  define CPLUSPLUS_BASE_LIBRARYSHARED_EXPORT BOOST_SYMBOL_EXPORT
#else
#  define CPLUSPLUS_BASE_LIBRARYSHARED_EXPORT BOOST_SYMBOL_IMPORT
#endif

#endif // CPLUSPLUS_BASE_LIBRARY_GLOBAL_HPP
